version: "3"

services:
  baxters_stuff:
    container_name: baxters_stuff
    build: .
    image: baxters_stuff:latest
    volumes:
      - data:/data/db
    networks:
      default:
        ipv4_address: 192.168.15.7

volumes:
  data:

networks:
  default:
    name: baxternet
