# Generated by Django 4.2.16 on 2025-04-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_alter_grocerylist_options_grocerylist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
