# Generated by Django 4.2.16 on 2025-04-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_alter_grocerylistitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
