# Generated by Django 4.2.16 on 2024-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(to='ingredient.ingredientcategory'),
        ),
    ]
